// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi62KECOqslyUpT2qASmOvQNE7XtilvYk',
    appId: '1:97515177046:web:3e8055789cc79cbe8667f7',
    messagingSenderId: '97515177046',
    projectId: 'conexion-flutter-b480e',
    authDomain: 'conexion-flutter-b480e.firebaseapp.com',
    storageBucket: 'conexion-flutter-b480e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-nE_jzHQ9inbZXl2eZ_WcP-iK2aF4jI',
    appId: '1:97515177046:android:ad139a8e959d4e608667f7',
    messagingSenderId: '97515177046',
    projectId: 'conexion-flutter-b480e',
    storageBucket: 'conexion-flutter-b480e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyu9-L7GfwHyYT9nwVecDhVE3Ay2bm40',
    appId: '1:97515177046:ios:70b5c13c932f7f7c8667f7',
    messagingSenderId: '97515177046',
    projectId: 'conexion-flutter-b480e',
    storageBucket: 'conexion-flutter-b480e.appspot.com',
    iosClientId: '97515177046-bt4f3eu4pbo7qjoo5i0hrnnhg184np7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConexion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyu9-L7GfwHyYT9nwVecDhVE3Ay2bm40',
    appId: '1:97515177046:ios:70b5c13c932f7f7c8667f7',
    messagingSenderId: '97515177046',
    projectId: 'conexion-flutter-b480e',
    storageBucket: 'conexion-flutter-b480e.appspot.com',
    iosClientId: '97515177046-bt4f3eu4pbo7qjoo5i0hrnnhg184np7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConexion',
  );
}
